// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDokDA1lIu-Oq-jkEOdAiwECB0OAQWD9ng',
    appId: '1:449504889748:web:c8aaee2de9c43c9b44dd81',
    messagingSenderId: '449504889748',
    projectId: 'fir-2-fa2f1',
    authDomain: 'fir-2-fa2f1.firebaseapp.com',
    storageBucket: 'fir-2-fa2f1.firebasestorage.app',
    measurementId: 'G-PG0WG85GD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsipQbeVqVDryT0XGVUcxAI1EZiq3ot-0',
    appId: '1:449504889748:android:1f00ba624ad1e80b44dd81',
    messagingSenderId: '449504889748',
    projectId: 'fir-2-fa2f1',
    storageBucket: 'fir-2-fa2f1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDokDA1lIu-Oq-jkEOdAiwECB0OAQWD9ng',
    appId: '1:449504889748:web:707a146b82e25d2b44dd81',
    messagingSenderId: '449504889748',
    projectId: 'fir-2-fa2f1',
    authDomain: 'fir-2-fa2f1.firebaseapp.com',
    storageBucket: 'fir-2-fa2f1.firebasestorage.app',
    measurementId: 'G-3DM3JWXZPM',
  );

}