// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ts5BEW8p5v7FcQPzc8Aq8rsUNldUOcI',
    appId: '1:258781372323:web:4dd6c74bf7d2e1838ac416',
    messagingSenderId: '258781372323',
    projectId: 'first-app-88b1b',
    authDomain: 'first-app-88b1b.firebaseapp.com',
    databaseURL: 'https://first-app-88b1b-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-88b1b.firebasestorage.app',
    measurementId: 'G-T1V8WGVEGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA06Mdtfm8_WK_aMi419gGf9IuBq1Ksar4',
    appId: '1:258781372323:android:74f49f0d3972062b8ac416',
    messagingSenderId: '258781372323',
    projectId: 'first-app-88b1b',
    databaseURL: 'https://first-app-88b1b-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-88b1b.firebasestorage.app',
  );
}
